### ISSUE TITLE
The fishing clicker is too fast for laggy servers

### ISSUE THREAD

**Issue by Cabeludo11** [monpjc/XAHK#15]
the fishing rod is reseting all the time  and dont actually fish

**Comment by RRR06** [comment]
You can modify the timing in between, but there is a slider which I think already does that, am not sure. But again, you can modify the timing, if you do I would recommend 1.5 seconds or 2 seconds. (Due to Minecraft mechanics, the max is 3.9, bc going over 4 seconds may cause you to lose the opportunity to catch the reward)

**Comment by monpjc** [comment]
I agree that there are issues with some servers and timming. This is something that was discussed and I released a 'As is' code to see how well it worked. Plan is to make 'all' timmings and ajustments user setable so this will get better. I also hope that in some way we can save configurations (timmings etc).

**Comment by monpjc** [comment]
See #7 for updates
