### ISSUE TITLE
The generator alt+tab fix wasn't compiled 

### ISSUE THREAD

**Issue by gigiodelchiaro** [monpjc/XAHK#42]
I know there is already an issue fixed that now allows for alt+tab in generator mode, but it wasn't put in any releases, only in the source code. It's been 7 months since the last commit, but 8 since the last release

**Comment by histefanhere** [comment]
No problem, I've published a new release now [that you can check out here](https://github.com/histefanhere/XAHK/releases).

And yeah, I know it's been a long time since the last release. I actually just recently found out that AutoHotkey v2 has released which fixes my biggest gripes with it so I'm very keen to start back up development on this. Just have to find the time! 😄
